# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '00 12 * * *' # run once a day at 12 utc
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: download pretrained model
      run: |
        mkdir -p pipeline/image_assessment/pretrained_model
        gdown 1TuK5ZPh7hW5f1-B0XCdH-xEToMiBikxn -O pipeline/image_assessment/pretrained_model/epoch-82.pth
    - name: download git submodule
      run: git submodule init
    - name: Run image assessment code
      run: |
        cd pipeline
        python run_once_per_day.py
